config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shops
  root "shops#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shop.rb
class Shop < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shop, only: %i[ show edit update destroy ]

  # GET /shops or /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1 or /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops or /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: "Shop was successfully created." }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: "Shop was successfully updated." }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    @shop.destroy!

    respond_to do |format|
      format.html { redirect_to shops_path, status: :see_other, notice: "Shop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:name, :details, :price, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="http://127.0.0.1:3000/">Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="http://127.0.0.1:3000/">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
    
    </ul>
        
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Devise Pun" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shops/_form.html.erb
<%= form_with(model: shop) do |form| %>
  <% if shop.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
        <% shop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :details, style: "display: block" %>
    <%= form.text_area :details %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/_shop.html.erb
<div id="<%= dom_id shop %>">
  <p>
    <strong>Name:</strong>
    <%= shop.name %>
  </p>

  <p>
    <strong>Details:</strong>
    <%= shop.details %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= shop.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= shop.quantity %>
  </p>

</div>

app/views/shops/edit.html.erb
<% content_for :title, "Editing shop" %>

<h1>Editing shop</h1>

<%= render "form", shop: @shop %>

<br>

<div>
  <%= link_to "Show this shop", @shop %> |
  <%= link_to "Back to shops", shops_path %>
</div>

app/views/shops/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Shops" %>
<%= link_to "Add New shop", new_shop_path %><br>
<% if signed_in? %>
  <%= button_to 'Log Out', destroy_user_session_path %>
 <% else %>
  <%= link_to 'Log In', new_user_session_path %>
  <%= link_to 'Sign Up', new_user_registration_path %>
<% end %>
<hr>
<div>
  <h1>All Shops</h1>

  <div id="shops">
    <% @shops.each do |shop| %>
      <%= render shop %>
      <p>
        <%= link_to "Show this shop", shop %>
      </p>
    <% end %>
  </div>
</div>

app/views/shops/new.html.erb
<% content_for :title, "New shop" %>

<h1>New shop</h1>

<%= render "form", shop: @shop %>

<br>

<div>
  <%= link_to "Back to shops", shops_path %>
</div>

app/views/shops/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shop %>

<div>
  <%= link_to "Edit this shop", edit_shop_path(@shop) %> |
  <%= link_to "Back to shops", shops_path %>

  <%= button_to "Destroy this shop", @shop, method: :delete %>
</div>